{{- if .Values.function }}{{ if .Values.function.autoready }}
{{- with .Values.function.autoready }}
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:{{ .version }}
---
{{- end }}
{{- end }}{{ end }}