{{- with .Values.provider.kubernetes }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/upbound/provider-kubernetes:{{ .version }}
---
{{- range $providers := .providers }}
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: {{ .name }}
spec:
  credentials:
    {{- .providerConfig.credentials | toYaml | trim | nindent 4 }}
---
{{- end }}
{{- end }}