apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: x-eks-component
spec:
  compositeTypeRef:
    apiVersion: consumable.trustbank.sg/v1alpha1
    kind: xEksComponent
  resources:
  - name: x-helm-metrics-server
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      metadata:
        name: xplane-helm-metrics-server
        annotations:
          crossplane.io/external-name: metrics-server
      spec:
        forProvider:
          chart:
            name: metrics-server
            repository: https://kubernetes-sigs.github.io/metrics-server/
            version: "3.12.1"
          namespace: metrics-server
          wait: true
        providerConfigRef:
          name: provider-helm
    patches:
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.clusterRef
        strategy: string
        string:
          fmt: "provider-helm-%s"
      toFieldPath: spec.providerConfigRef.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.components.metrics-server.version
      toFieldPath: spec.forProvider.chart.version