apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xekscomponents.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xEksComponent
    plural: xekscomponents
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              clusterRef:
                type: string
              components:
                type: object
                properties:
                  metrics-server:
                    type: object
                    properties:
                      version:
                        type: string
            required:
            - name
    served: true
    referenceable: true
  claimNames:
    kind: EksComponent
    plural: ekscomponents