apiVersion: consumable.trustbank.sg/v1alpha1
kind: xNetwork
metadata:
  name: eksac-vpc01
  namespace: eksac
spec:
  name: eksac-vpc01
  location: "ap-southeast-1"
  vpcCidr: "10.0.0.0/22"
  subnets:
    public:
      z1Cidr: "10.0.0.0/28"
      z2Cidr: "10.0.0.16/28"
      z3Cidr: "10.0.0.32/28"
---
apiVersion: consumable.trustbank.sg/v1alpha1
kind: Network
metadata:
  name: eksac-vpc01
  namespace: eksac
spec:
  name: eksac-vpc01
  resourceRef:
    apiVersion: consumable.trustbank.sg/v1alpha1
    kind: xNetwork
    name: eksac-vpc01