apiVersion: consumable.trustbank.sg/v1alpha1
kind: xEksCluster
metadata:
  name: eksac-cluster02
  namespace: eksac
spec:
  name: eksac-cluster02
  location: "ap-southeast-1"
  awsAccountId: "390945758345"
  vpcRef: eksac-vpc01
  subnets:
    private:
      z1Cidr: "10.0.2.0/25"
      z2Cidr: "10.0.2.128/25"
      z3Cidr: "10.0.3.0/25"
  components:
    ciliumHelm:
      version: "1.16.1"
    corednsAddOn:
      version: "v1.11.1-eksbuild.11"
    ebscsiAddOn:
      version: "v1.33.0-eksbuild.1"
    eks:
      version: "1.30"
    karpenterHelm:
      version: "1.0.1"
---
apiVersion: consumable.trustbank.sg/v1alpha1
kind: EksCluster
metadata:
  name: eksac-cluster02
  namespace: eksac
spec:
  name: eksac-cluster02
  resourceRef:
    apiVersion: consumable.trustbank.sg/v1alpha1
    kind: xEksCluster
    name: eksac-cluster02