apiVersion: consumable.trustbank.sg/v1alpha1
kind: xEksCluster
metadata:
  name: eksac-cluster02
spec:
  name: eksac-cluster02
  location: "ap-southeast-1"
  awsAccountId: "390945758345"
  vpcRef: sandbox-eksac01
  subnets:
    private:
      z1Cidr: "10.0.1.0/26"
      z2Cidr: "10.0.1.64/26"
      z3Cidr: "10.0.1.128/26"
  components:
    eks:
      version: "1.30"
---
apiVersion: consumable.trustbank.sg/v1alpha1
kind: EksCluster
metadata:
  name: eksac-cluster02
spec:
  name: eksac-cluster02
  resourceRef:
    apiVersion: consumable.trustbank.sg/v1alpha1
    kind: xEksCluster
    name: eksac-cluster02