apiVersion: consumable.trustbank.sg/v1alpha1
kind: NetworkKcl
metadata:
  name: linus-network
  namespace: eksac
spec:
  name: linus-network
  location: "ap-southeast-1"
  vpcCidr: "10.0.0.0/22"
  subnets:
    public:
      1a: "10.0.0.0/28"
      1b: "10.0.0.16/28"
      1c: "10.0.0.32/28"
---
apiVersion: consumable.trustbank.sg/v1alpha1
kind: EksClusterKcl
metadata:
  name: linus-cluster
  namespace: eksac
spec:
  name: linus-cluster
  location: "ap-southeast-1"
  awsAccountId: "390945758345"
  vpcRef: linus-network
  subnets:
    private:
      1a: "10.0.0.128/25"
      1b: "10.0.1.0/25"
      1c: "10.0.1.128/25"
  components:
    ciliumHelm:
      version: "1.17.3"
    corednsHelm:
      version: "1.41.0"
    ebscsiAddOn:
      version: "v1.42.0-eksbuild.1"
    podidentityagentAddOn:
      version: "v1.3.5-eksbuild.2"
    eks:
      version: "1.32"
    karpenterHelm:
      version: "1.4.0"