apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: x-network
spec:
  compositeTypeRef:
    apiVersion: consumable.trustbank.sg/v1alpha1
    kind: xNetwork
  patchSets:
  - name: region-patchset
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.location"
      toFieldPath: "spec.forProvider.region"
      transforms:
        - type: map
          map: 
            HKG: "ap-east-1"
            SGP: "ap-southeast-1"
            SYD: "ap-southeast-2"
            JKT: "ap-southeast-3"
  - name: vpcid-patchset
    patches:
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-vpc"
      toFieldPath: spec.forProvider.vpcIdRef.name
  resources:
  - name: xvpc
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VPC
      metadata:
        name: xplane-vpc
      spec:
        deletionPolicy: Delete
        forProvider:
          region: ap-southeast-1
          cidrBlock: 10.0.0.0/16
          enableDnsHostnames: true
          enableDnsSupport: true
          tags:
            Name: xplane-vpc
            Owner: linus.yong
            Environment: sandbox
            Project: crossplane
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-vpc"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-vpc"
      toFieldPath: spec.forProvider.tags.Name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.vpcCidr
      toFieldPath: spec.forProvider.cidrBlock
  - name: xsubnet-z1
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: xplane-subnet-1a
      spec:
        deletionPolicy: Delete
        forProvider:
          region: ap-southeast-1
          availabilityZone: ap-southeast-1a
          cidrBlock: 10.0.100.0/24
          tags:
            Name: xplane-subnet-1a
            Owner: linus.yong
            Environment: sandbox
            Project: crossplane
          vpcIdRef:
            name: xplane-vpc
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
    - type: PatchSet
      patchSetName: vpcid-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-subnet-1a"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-subnet-1a"
      toFieldPath: spec.forProvider.tags.Name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.subnets.z1Cidr
      toFieldPath: spec.forProvider.cidrBlock
  - name: xsubnet-z2
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: xplane-subnet-1b
      spec:
        deletionPolicy: Delete
        forProvider:
          region: ap-southeast-1
          availabilityZone: ap-southeast-1b
          cidrBlock: 10.0.101.0/24
          tags:
            Name: xplane-subnet-1b
            Owner: linus.yong
            Environment: sandbox
            Project: crossplane
          vpcIdRef:
            name: xplane-vpc
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
    - type: PatchSet
      patchSetName: vpcid-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-subnet-1b"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-subnet-1b"
      toFieldPath: spec.forProvider.tags.Name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.subnets.z2Cidr
      toFieldPath: spec.forProvider.cidrBlock
  - name: xsubnet-z3
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: xplane-subnet-1c
      spec:
        deletionPolicy: Delete
        forProvider:
          region: ap-southeast-1
          availabilityZone: ap-southeast-1c
          cidrBlock: 10.0.102.0/24
          tags:
            Name: xplane-subnet-1c
            Owner: linus.yong
            Environment: sandbox
            Project: crossplane
          vpcIdRef:
            name: xplane-vpc
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
    - type: PatchSet
      patchSetName: vpcid-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-subnet-1c"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-subnet-1c"
      toFieldPath: spec.forProvider.tags.Name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.subnets.z3Cidr
      toFieldPath: spec.forProvider.cidrBlock
  - name: xigw
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: InternetGateway
      metadata:
        name: xplane-igw
      spec:
        deletionPolicy: Delete
        forProvider:
          region: ap-southeast-1
          tags:
            Name: xplane-igw
            Owner: linus.yong
            Environment: sandbox
            Project: crossplane
        vpcIdRef:
          name: xplane-vpc
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
    - type: PatchSet
      patchSetName: vpcid-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-igw"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-igw"
      toFieldPath: spec.forProvider.tags.Name
  - name: xdrt
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: DefaultRouteTable
      metadata:
        name: xplane-drt
      spec:
        deletionPolicy: Orphan
        forProvider:
          defaultRouteTableIdRef:
            name: xplane-vpc
          region: ap-southeast-1
          route:
          - cidrBlock: 0.0.0.0/0
            gatewayIdRef:
              name: xplane-igw
          tags:
            Name: xplane-drt
            Owner: linus.yong
            Environment: sandbox
            Project: crossplane
          vpcIdRef:
            name: xplane-vpc
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
    - type: PatchSet
      patchSetName: vpcid-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-drt"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-igw"
      toFieldPath: spec.forProvider.tags.Name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-vpc"
      toFieldPath: spec.forProvider.defaultRouteTableIdRef.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-igw"
      toFieldPath: spec.forProvider.route.gatewayIdRef.name