apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xNetwork
    plural: xnetworks
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              location:
                type: string
                oneOf:
                - pattern: '^HKG$'
                - pattern: '^SGP$'
                - pattern: '^SYD$'
                - pattern: '^JKT$'
              vpcCidr:
                type: string
              subnets:
                type: object
                properties:
                  public:
                    type: object
                    properties:
                      z1Cidr:
                        type: string
                      z2Cidr:
                        type: string
                      z3Cidr:
                        type: string
                  private:
                    type: object
                    properties:
                      z1Cidr:
                        type: string
                      z2Cidr:
                        type: string
                      z3Cidr:
                        type: string
            required:
            - name
            - location
          status:
            type: object
            properties:
              natGatewayId:
                type: string
    served: true
    referenceable: true
  claimNames:
    kind: Network
    plural: networks
