apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xekscomponents.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xEksComponents
    plural: xekscomponents
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              clusterRef:
                type: string
              components:
                type: object
                properties:
                  aws-loadbalancer-controller-helm:
                    type: object
                    properties:
                      version:
                        type: string
                  metrics-server-helm:
                    type: object
                    properties:
                      version:
                        type: string
                  vault-helm:
                    type: object
                    properties:
                      version:
                        type: string
            required:
            - name
          status:
            type: object
            properties:
              awsAccountId:
                type: string
              oidcIssuer:
                type: string
              karpenterFargateStatus:
                type: string
    served: true
    referenceable: true
  claimNames:
    kind: EksComponents
    plural: ekscomponents