apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: x-eks-cluster
spec:
  writeConnectionSecretsToNamespace: eksac
  compositeTypeRef:
    apiVersion: consumable.trustbank.sg/v1alpha1
    kind: xEksCluster
  patchSets:
  - name: region-patchset
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.location"
      toFieldPath: "spec.forProvider.region"
      transforms:
        - type: map
          map: 
            HKG: "ap-east-1"
            SGP: "ap-southeast-1"
            SYD: "ap-southeast-2"
            JKT: "ap-southeast-3"
  - name: vpcid-patchset
    patches:
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-vpc"
      toFieldPath: spec.forProvider.vpcIdRef.name
  resources:
  - name: x-iam
    base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: Role
      metadata:
        name: xplane-eks-iam
      spec:
        deletionPolicy: Delete
        forProvider:
          assumeRolePolicy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "eks.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
                }
              ]
            }
          managedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
          tags:
            Name: xplane-eks-iam
            Owner: linus.yong
            Environment: sandbox
        providerConfigRef:
          name: aws-provider
    patches:
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-iam"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-iam"
      toFieldPath: spec.forProvider.tags.Name
  - name: x-securitygroup-eks-cluster
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroup
      metadata:
        name: xplane-eks-sg-cluster
      spec:
        deletionPolicy: Delete
        forProvider:
          groupName: xplane-eks-sg-cluster
          description: "Security Group for EKS Control Plane"
          region: ap-southeast-1
          vpcIdRef:
            name: xplane-vpc
          tags:
            Name: xplane-eks-sg-cluster
            Owner: linus.yong
            Environment: sandbox
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
      patchSetName: vpcid-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-sg-cluster"
      toFieldPath: spec.forProvider.groupName
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-sg-cluster"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-sg-cluster"
      toFieldPath: spec.forProvider.tags.Name
  - name: x-securitygroup-eks-node
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: SecurityGroup
      metadata:
        name: xplane-eks-sg-node
      spec:
        deletionPolicy: Delete
        forProvider:
          groupName: xplane-eks-sg-node
          description: "Security Group for EKS Nodes"
          region: ap-southeast-1
          vpcIdRef:
            name: xplane-vpc
          tags:
            Name: xplane-eks-sg-node
            Owner: linus.yong
            Environment: sandbox
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
      patchSetName: vpcid-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-sg-node"
      toFieldPath: spec.forProvider.groupName
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-sg-node"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-sg-node"
      toFieldPath: spec.forProvider.tags.Name
  - name: x-eks
    base:
      apiVersion: eks.aws.upbound.io/v1beta1
      kind: Cluster
      metadata:
        name: xplane-eks-cluster
      spec:
        deletionPolicy: Delete
        forProvider:
          region: ap-southeast-1
          roleArnRef:
            name: xplane-eks-iam
          version: "1.29"
          vpcConfig:
          - endpointPrivateAccess: true
            endpointPublicAccess: true
            subnetIdRefs:
            - name: xplane-private-subnet-1a
            - name: xplane-private-subnet-1b
            - name: xplane-private-subnet-1c
            securityGroupIdSelector:
              matchControllerRef: true
          tags:
            Name: xplane-eks-cluster
            Owner: linus.yong
            Environment: sandbox
        writeConnectionSecretToRef:
          namespace: eksac
          name: xplane-eks-cluster-connection
        providerConfigRef:
          name: aws-provider
    patches:
    - type: PatchSet
      patchSetName: region-patchset
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-cluster"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-cluster"
      toFieldPath: spec.forProvider.tags.Name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-iam"
      toFieldPath: spec.forProvider.roleArnRef.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-private-subnet-1a"
      toFieldPath: spec.forProvider.vpcConfig[0].subnetIdRefs[0].name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-private-subnet-1b"
      toFieldPath: spec.forProvider.vpcConfig[0].subnetIdRefs[1].name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-private-subnet-1c"
      toFieldPath: spec.forProvider.vpcConfig[0].subnetIdRefs[2].name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-cluster-connection"
      toFieldPath: spec.writeConnectionSecretToRef.name
    connectionDetails:
    - name: cluster-ca
      fromConnectionSecretKey: clusterCA
    - name: apiserver-endpoint
      fromConnectionSecretKey: endpoint
    - name: value
      fromConnectionSecretKey: kubeconfig