apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: x-eks-cluster
spec:
  compositeTypeRef:
    apiVersion: consumable.trustbank.sg/v1alpha1
    kind: xEksCluster
  patchSets: []
  resources:
  - name: x-iam
    base:
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: Role
      metadata:
        name: xplane-eks-iam
      spec:
        deletionPolicy: Delete
        forProvider:
          assumeRolePolicy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "eks.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole"
                }
              ]
            }
          managedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
          tags:
            Name: xplane-eks-iam
            Owner: linus.yong
            Environment: sandbox
        providerConfigRef:
          name: aws-provider
    patches:
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-iam"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.name
        strategy: string
        string:
          fmt: "%s-xplane-eks-iam"
      toFieldPath: spec.forProvider.tags.Name