apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksclusters.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xEksCluster
    plural: xeksclusters
  connectionSecretKeys:
  - cluster-ca
  - apiserver-endpoint
  - value
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              location:
                type: string
                oneOf:
                - pattern: '^HKG$'
                - pattern: '^SGP$'
                - pattern: '^SYD$'
                - pattern: '^JKT$'
            required:
            - name
            - location
          status:
            type: object
            properties:
              oidcIssue":
                type: string
          status:
            type: object
            properties:
              oidcIssuer:
                type: string
    served: true
    referenceable: true
  claimNames:
    kind: EksCluster
    plural: eksclusters