apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xekscluster.consumable.trustbank.sg
spec:
  group: consumable.trustbank.sg
  names:
    kind: xEksCluster
    plural: xeksclusters
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
            required:
            - name
    served: true
    referenceable: true
  claimNames:
    kind: EksCluster
    plural: eksclusters