provider:
  awsFamily:
    name: aws-provider
    accountId: "390945758345"
    crossplaneIamRoleName: "eksac-crossplane-iam-role"
    region: ap-southeast-1
    deploymentRuntimeConfig:
      name: aws-deployment-runtime-config
      deploymentTemplate:
        spec:
          replicas: 1
    version: v1
    # version: v1.23.1
    providers:
    - name: provider-aws-ec2
      providerConfig:
        credentials:
          source: IRSA
    - name: provider-aws-eks
      providerConfig:
        credentials:
          source: IRSA
    - name: provider-aws-iam
      providerConfig:
        credentials:
          source: IRSA
  helm:
    version: v0
    # version: v0.21.1
  kubernetes:
    version: v0
    # version: v0.18.1
    providers:
    - name: provider-kubernetes
      providerConfig:
        credentials:
          source: InjectedIdentity
function:
  kcl:
    version: v0.11.4
  autoready:
    version: v0.5.0
  sequencer:
    version: v0.2.3